export const config = {
  name: "Luyao",
  email: "shzu_luyao@163.com",
  github: "https://github.com/YaoYaoSuperman",
  
  papers: [
    {
      id: 1,
      title: "轻量级多标签水果图像分类优化研究",
      titleEn: "Lightweight and Optimized Multi-Label Fruit Image Classification",
      journal: "Electronics (SCI Q2)",
      role: "第二作者 (核心贡献者)",
      roleEn: "2nd Author (Key contributor)",
      technologies: ["知识蒸馏", "MobileNet/DenseNet", "图像增强"],
      technologiesEn: ["Knowledge Distillation", "MobileNet/DenseNet", "Image Enhancement"],
      url: "https://www.mdpi.com/2079-9292/10/11/3941",
      doi: "10.3390/electronics10113941",
    },
    {
      id: 2,
      title: "用于肺炎分类的轻量级 Res-Net (LR-Net)",
      titleEn: "A Lightweight Res-Net (LR-Net) For Pneumonia Classification",
      journal: "EI 国际会议",
      role: "第一作者",
      roleEn: "1st Author",
      technologies: ["ResNet18", "深度可分离卷积"],
      technologiesEn: ["ResNet18", "Depthwise Separable Convolution"],
      url: "https://github.com/YaoYaoSuperman/pneumonia-classification",
      doi: "",
    },
  ],

  projects: [
    {
      id: 1,
      title: "基于扩散模型的离线手写签名生成及鉴定",
      titleEn: "Offline Handwritten Signature Generation & Verification based on Diffusion Models",
      role: "项目负责人 (国家级创新项目)",
      roleEn: "Project Lead (National Innovation Project)",
      description: "利用先进的扩散模型技术生成高质量伪造签名,用于训练更鲁棒的签名鉴定系统。该项目结合了 AIGC 前沿技术和深度学习,在数字取证和生物识别领域具有重要应用价值。",
      technologies: [
        { name: "扩散模型", icon: "Wand2" },
        { name: "U-Net", icon: "Cpu" },
        { name: "AIGC", icon: "Rocket" },
        { name: "ResNet", icon: "Shield" },
      ],
      githubUrl: "https://github.com/YaoYaoSuperman/signature-diffusion",
      demoUrl: "",
      tags: ["深度学习", "计算机视觉", "数字取证"],
    },
  ],

  awards: [
    {
      id: 1,
      title: "ICPC (ACM) 中国新疆区域赛",
      titleEn: "ICPC (ACM) China Xinjiang Regional",
      achievement: "金牌 (队长)",
      achievementEn: "Gold Medal (Team Captain)",
      icon: "Trophy",
      color: "from-yellow-500 to-orange-500",
      year: "2024",
    },
    {
      id: 2,
      title: "MCM/ICM 美国大学生数学建模竞赛",
      titleEn: "Mathematical Contest in Modeling",
      achievement: "国际二等奖 (队长)",
      achievementEn: "International 2nd Prize (Team Captain)",
      icon: "Medal",
      color: "from-blue-500 to-indigo-500",
      year: "2024",
    },
    {
      id: 3,
      title: "国家奖学金",
      titleEn: "National Scholarship",
      achievement: "本科生最高荣誉",
      achievementEn: "Highest Honor for Undergraduates",
      icon: "Award",
      color: "from-purple-500 to-pink-500",
      year: "2024",
    },
    {
      id: 4,
      title: "全国大学生计算机能力挑战赛 (C++)",
      titleEn: "National College Student Computer Ability Challenge",
      achievement: "全国一等奖",
      achievementEn: "National 1st Prize",
      icon: "Star",
      color: "from-cyan-500 to-blue-500",
      year: "2024",
    },
  ],
}
